#!/bin/bash

INTERN_MODEL="InternVL3_5-8B"
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_Base_55/${INTERN_MODEL}/${INTERN_MODEL}_MMStar_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_Base_55/${INTERN_MODEL}/${INTERN_MODEL}_MME_score.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_Base_55/${INTERN_MODEL}/${INTERN_MODEL}_ScienceQA_VAL_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_Base_55/${INTERN_MODEL}/${INTERN_MODEL}_RealWorldQA_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_Base_55/${INTERN_MODEL}/${INTERN_MODEL}_BLINK_acc.csv

echo "✅ Extracting VGD results"
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_VGD_55/${INTERN_MODEL}/${INTERN_MODEL}_MMStar_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_VGD_55/${INTERN_MODEL}/${INTERN_MODEL}_MME_score.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_VGD_55/${INTERN_MODEL}/${INTERN_MODEL}_ScienceQA_VAL_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_VGD_55/${INTERN_MODEL}/${INTERN_MODEL}_RealWorldQA_acc.csv
cat outputs/${INTERN_MODEL}/${INTERN_MODEL}_VGD_55/${INTERN_MODEL}/${INTERN_MODEL}_BLINK_acc.csv